### ISSUE TITLE
Daily Cash Counter

### ISSUE THREAD

**Issue by failuresx** [kokspflanze/PServerCore#1]
Hey,

Counter like x/100000 Cash per day.. if achieved the 100000 cash, every user receives 20% more.

**Comment by banmaschine** [comment]
Good idea with an Loading bar on website where you see how far the Bonus is away :dancer:

**Comment by kokspflanze** [comment]
see also https://github.com/kokspflanze/PServerCore/issues/3

**Comment by kokspflanze** [comment]
migration to https://github.com/PServerCMS/DonateAction/issues/1

**Comment by kokspflanze** [comment]
https://github.com/PServerCMS/DonateAction/commit/9f81c578a3fbc1367b59d79ccd60e09dacc039eb
