### ISSUE TITLE
Donation Reward

### ISSUE THREAD

**Issue by banmaschine** [kokspflanze/PServerCore#3]
System like users that donated:

10k Coin get automaticly +2% Coins on every order
20k Coin get automaticly +3% Coins on every order
30k Coin get automaticly +4% Coins on every order
50k Coin get automaticly +5% Coins on every order

and so on but individuell configurable ;)

**Comment by kokspflanze** [comment]
startet @ https://github.com/PServerCMS/DonateAction

basic parts are also done
